# Generated by Django 5.2.7 on 2025-10-27 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pertanyaan", models.CharField(max_length=255)),
                ("jawaban", models.TextField()),
                (
                    "kategori",
                    models.CharField(
                        blank=True,
                        help_text="Contoh: fasilitas, reservasi, umum",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FasilitasUmum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_fasilitas", models.CharField(max_length=100)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("jam_buka", models.CharField(blank=True, max_length=50, null=True)),
                ("lokasi", models.CharField(blank=True, max_length=100, null=True)),
                ("gambar_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kamar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_kamar", models.CharField(max_length=10, unique=True)),
                (
                    "tipe_kamar",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard"),
                            ("Deluxe", "Deluxe"),
                            ("Suite", "Suite"),
                        ],
                        default="Standard",
                        max_length=50,
                    ),
                ),
                (
                    "harga_per_malam",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "kapasitas",
                    models.IntegerField(default=2, help_text="Jumlah maksimal tamu"),
                ),
                (
                    "fasilitas",
                    models.TextField(
                        help_text="Fasilitas di kamar, pisahkan dengan koma"
                    ),
                ),
                (
                    "diskon_persen",
                    models.IntegerField(
                        default=0, help_text="Diskon dalam persen, misal: 15 untuk 15%"
                    ),
                ),
                (
                    "catatan_diskon",
                    models.CharField(
                        blank=True,
                        help_text="Contoh: Promo Akhir Pekan!",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "url_gambar",
                    models.URLField(
                        blank=True,
                        help_text="URL gambar kamar yang bisa diakses publik",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pelayanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_layanan", models.CharField(max_length=100)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                (
                    "biaya",
                    models.DecimalField(
                        decimal_places=2, help_text="Biaya layanan (Rp)", max_digits=10
                    ),
                ),
                (
                    "jam_operasional",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gambar_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_tamu", models.CharField(max_length=100)),
                ("tanggal_check_in", models.DateTimeField()),
                ("tanggal_check_out", models.DateTimeField()),
                (
                    "kamar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_hotel.kamar",
                    ),
                ),
            ],
        ),
    ]
