# Generated by Django 5.2.7 on 2025-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(default="Hotel Maju Jaya", max_length=200)),
                ("alamat", models.TextField(blank=True, null=True)),
                ("kota", models.CharField(blank=True, max_length=100, null=True)),
                ("negara", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("telepon", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("jam_check_in", models.TimeField(blank=True, null=True)),
                ("jam_check_out", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Informasi Hotel",
                "verbose_name_plural": "Informasi Hotel",
            },
        ),
    ]
