# Generated by Django 5.2.7 on 2025-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_hotel", "0002_hotelinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelinfo",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="URL website resmi hotel, misal: https://www.hotelmajujaya.com",
                max_length=300,
                null=True,
            ),
        ),
    ]
