# Generated by Django 5.2.8 on 2025-11-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(default="SMAN 1 Jakarta (Django)", max_length=100),
                ),
                ("academic_year", models.CharField(default="2025/2026", max_length=20)),
                ("semester", models.CharField(default="Ganjil", max_length=20)),
                ("start_time", models.CharField(default="07:00", max_length=10)),
                ("end_time", models.CharField(default="15:00", max_length=10)),
                ("notifications", models.BooleanField(default=True)),
                ("language", models.CharField(default="id", max_length=10)),
                ("theme", models.CharField(default="light", max_length=10)),
            ],
        ),
    ]
