# Generated by Django 5.2.7 on 2026-03-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=100, verbose_name='Nama Mahasiswa')),
                ('barang_dipinjam', models.CharField(max_length=200)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status_dikembalikan', models.BooleanField(default=False, verbose_name='Sudah Dikembalikan?')),
            ],
        ),
    ]
